config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'searches/search'
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers:{
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to:"public/homes#top"
  scope module: :public do
    get 'users/confirm' => 'users#confirm'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :update, :edit] do
      get :bookmarks, on: :collection
      resource :relationships, only: [:create, :destroy]
      get 'relationships/followings' => 'relationships#followings', as: 'followings'
      get 'relationships/followers' => 'relationships#followers', as: 'followers'
    end
    get 'search' => 'searches#search'
    get 'tag_search' => 'searches#tag_search'
    resources :posts do
      resource :bookmarks, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:new, :create, :destroy]
    end
  end

  namespace :admin do
    get 'homes/top' => 'homes#top', as: 'top'
    resources :posts, only: [:show]
    resources :users, only: [:index, :show, :edit, :update]
  end

  devise_scope :user do #deviseを使用して新しくルーティング作成
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @posts = Post.page(params[:page]).per(10)
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/_admin_side.html.erb
<div class="sidebar border bg-white py-3">
  <ul>
    <li>
      <p class="h5 mt-4 mb-3"><%= link_to'ユーザ一覧', admin_users_path, class:"text-decoration-none" %></p>
    </li>
    <li>
      <p class="h5 mt-4"><%= link_to'投稿一覧', admin_top_path, class:"text-decoration-none" %></p>
    </li>
    <li>
      <p class="h5 mt-4"><%= link_to'ログアウト', destroy_admin_session_path, method: :delete, class:"text-decoration-none" %></p>
    </li>
  </ul>
</div>

app/views/admin/homes/top.html.erb
<div class="container-fluid">
  <div class="row my-2">
    <h3 class="col-md-4 col-sm-5 text-center mx-5"><strong>投稿一覧</strong></h3>
  </div>

  <div class="row justify-content-center">
    <div class="col-md-3 col-sm-8 mx-5 mb-5 p-0">
      <%= render'admin_side' %>
    </div>

    <div class="bg-light border col-md-6 col-sm-10 pt-3 mb-3">
      <table class="col-md-10 col-sm-9 mx-auto mb-3 text-center">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">ユーザ名</th>
              <th scope="col">投稿日</th>
              <th scope="col">商品名</th>
            </tr>
          </thead>
          <tbody class="border bg-white">
            <% @posts.each do |post| %>
            <tr class="border-bottom" data-href="/admin/posts/<%= post.id %>">
              <td><%= image_tag post.user.get_profile_image(100,100), class:"rounded-circle profile-icon" %></td>
              <td><%= post.user.name %></td>
              <td><%= post.created_at.strftime("%Y/%m/%d") %></td>
              <td><%= post.name %></td>
            </tr>
            <% end %>
          </tbody>
      </table>
      <%= paginate @posts %>
    </div>
  </div>
</div>