config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'searches/search'
  end
  devise_for :admin, skip: [:registrations, :passwords], controllers:{
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root to:"public/homes#top"
  scope module: :public do
    get 'users/confirm' => 'users#confirm'
    patch 'users/withdraw' => 'users#withdraw'
    resources :users, only: [:show, :update, :edit] do
      get :bookmarks, on: :collection
      resource :relationships, only: [:create, :destroy]
      get 'relationships/followings' => 'relationships#followings', as: 'followings'
      get 'relationships/followers' => 'relationships#followers', as: 'followers'
    end
    get 'search' => 'searches#search'
    get 'tag_search' => 'searches#tag_search'
    resources :posts do
      resource :bookmarks, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:new, :create, :destroy]
    end
  end

  namespace :admin do
    get 'homes/top' => 'homes#top', as: 'top'
    resources :posts, only: [:show]
    resources :users, only: [:index, :show, :edit, :update]
  end

  devise_scope :user do #deviseを使用して新しくルーティング作成
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FleurCrayon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/09b1dd4dc3.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Caveat&family=New+Tegomin&family=Zen+Kurenaido&display=swap" rel="stylesheet">

  </head>

  <body class="d-flex flex-column vh-100">
    <header class="border-bottom border-dark">
      <nav class="navbar navbar-expand-md navbar-light">
      <div class="container-fluid">
        <% if user_signed_in? %>
          <a class="title navbar-brand px-3" href="/posts">Fleur Crayon</a>
        <% else %>
          <a class="title navbar-brand p-3">Fleur Crayon</a>
        <% end %>
        <button class="navbar-toggler bg-white" type="button" data-toggle="collapse"
        data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav align-items-center ml-auto">
          <% if current_user %>
            <li class="nav-item mr-2">
              <%= image_tag current_user.get_profile_image(100,100), class:"rounded-circle profile-icon" %>
            </li>
            <li class="nav-item mr-4">
              <%= current_user.name %>
            </li>
            <li class="nav-item">
              <%= form_with url: search_path, method: :get do |form| %>
                <%= form.text_field :keyword, placeholder:"検索" %>
                <%= form.select :range, options_for_select([['投稿','Post'],['ユーザー','User']]) %>
                <%= form.submit "検索" %>
              <% end %>
              <%= form_with url: tag_search_path, method: :get do |form| %>
                <%= form.collection_select :tag_search, Tag.all, :tag_name, :tag_name, options = {include_blank: "タグ選択", disabled: true} %>
                <%= form.submit "タグ検索" %>
              <% end %>
            </li>
          <% else %>
            <li>管理者</li>
          <% end %>
          </ul>
        </div>
      </div>
      </nav>
    </header>
    <main class="main flex-grow-1">
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </main>
    <footer class="border-top border-light">
      <div class="container">
        <div class="row no-gutters">
          <h2 class="title mt-1 mb-5 text-white">Fleur Crayon</h2>
          <div class="footer-item ml-auto my-auto">
            <strong><%= link_to'退会', users_confirm_path, class:'text-white text-decoration-none' %></strong>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FleurCrayon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/09b1dd4dc3.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="card card-top">
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <div class="card-body d-flex align-items-center mb-5">
        <%= yield %>
      </div>
    </div>
  </body>
</html>